# Generated by Django 4.2.19 on 2025-03-07 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('last_year_revenue', models.DecimalField(decimal_places=2, max_digits=15)),
                ('last_year_profit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('revenue_year_3', models.DecimalField(decimal_places=2, max_digits=15)),
                ('revenue_year_2', models.DecimalField(decimal_places=2, max_digits=15)),
                ('revenue_year_1', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valuation', models.DecimalField(decimal_places=2, max_digits=15)),
                ('company_equity_percentage', models.DecimalField(decimal_places=2, max_digits=15)),
                ('profit_year_3', models.DecimalField(decimal_places=2, max_digits=15)),
                ('profit_year_2', models.DecimalField(decimal_places=2, max_digits=15)),
                ('profit_year_1', models.DecimalField(decimal_places=2, max_digits=15)),
                ('office_address', models.TextField()),
                ('government_certificate', models.FileField(upload_to='certificates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entrepreneur', models.ForeignKey(limit_choices_to={'user_type': 'entrepreneur'}, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
