# Generated by Django 4.2.19 on 2025-03-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='first_login',
            field=models.BooleanField(default=True),
        ),
    ]
