# Generated by Django 4.2.19 on 2025-03-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneur', '0002_customuser_first_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='available_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
