# Generated by Django 4.2.19 on 2025-03-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneur', '0004_remove_customuser_available_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='available_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
